import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Waggin Rights</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Image className={styles.dogs} src="/logo.jpg" alt="title" width={300} height={300}  />
      
        <h1 className={styles.title}>


          <a href="#scheduling">Waggin' Rights</a>
        </h1>

      

        <div className={styles.grid}>
          <a href="#scheduling" className={styles.card}>
            <h2>15 Minute Visit &rarr;</h2>
            <Image src="/fifteen_minute.jpg" alt="15 minute visit" width={600} height={600}  />
            <p>Get a 15 minute scheduled Today!</p>
          </a>

          <a href="#scheduling" className={styles.card}>
            <h2>30 Minute Visit &rarr;</h2>
            <Image src="/thirty_minute.jpg" alt="30 Minutevisit" width={600} height={600}  />
            <p>Get a 30 minute scheduled Today!</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>60 Minute Visit &rarr;</h2>
            <Image src="/sixty_minute.jpg" alt="60 Minutevisit" width={600} height={600}  />
            <p>Get a 60 minute scheduled Today!</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Overnights &rarr;</h2>
            <Image src="/overnights.jpg" alt="30 Minutevisit" width={600} height={600}  />
            <p>
              Get an Overnight scheduled Today!
            </p>
          </a>
          <a
            href="#"
            className={styles.card}
          >
            <h2>Packages & Pricing &rarr;</h2>
            <Image src="/specials.jpg" alt="Price List" width={600} height={600}  />
            <p>
              Here's a Full Overview of the packages & Pricing!
            </p>
          </a>
        </div>
      </main>
      <Image src="/title.jpg" alt="title" width={600} height={300}  />
      <footer className={styles.footer}>
        <a
          href="#scheduling"
          target="_blank"
          rel="noopener noreferrer"
        >
          Lovingly Established by{' '}
          <span className={styles.logo}>
            <Image className={styles.emz} src="/emily.jpeg" alt="Emily and Daughter" width={50} height={50} />
          </span>
        </a>
       <p className={styles.emz_para}> Emily Griffith</p>
      </footer>
    </div>
  )
}
